# Generated by Django 5.2 on 2025-06-03 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=100)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='administration/')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(default='Votre slogan ici', max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='administration/')),
                ('description', models.TextField(default='')),
                ('primary_color', models.CharField(default='#ff385c', max_length=7)),
                ('font_family', models.CharField(default="'Poppins', sans-serif", max_length=100)),
                ('cta_text', models.CharField(default='Découvrir nos logements', max_length=100)),
                ('contact_title', models.CharField(default='Contactez-nous', max_length=100)),
            ],
            options={
                'verbose_name': "Configuration de la page d'accueil",
                'verbose_name_plural': "Configuration de la page d'accueil",
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='administration/')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='administration.homepageconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-star', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='administration/')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='administration.homepageconfig')),
            ],
            options={
                'verbose_name': "Configuration de la page d'accueil",
                'verbose_name_plural': "Configuration de la page d'accueil",
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('path', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='administrat_timesta_16aa48_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testimonials', to='administration.homepageconfig')),
            ],
        ),
    ]
