# Generated by Django 5.2 on 2025-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='form',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
