# Generated by Django 5.2 on 2025-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttask',
            name='task_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttask',
            name='type',
            field=models.CharField(choices=[('transfer_owner', 'Transfer to Owner'), ('transfer_admin', 'Transfer to Admin'), ('charge_deposit', 'Charge Deposit'), ('refund', 'Refund'), ('checkout', 'Check Out')], max_length=20),
        ),
    ]
