# Generated by Django 5.2 on 2025-06-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0002_paymenttask_task_id_alter_paymenttask_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttask',
            name='unique_task_type_per_reservation',
        ),
        migrations.RemoveField(
            model_name='paymenttask',
            name='reservation',
        ),
        migrations.AddField(
            model_name='paymenttask',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttask',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttask',
            name='type',
            field=models.CharField(choices=[('transfer_owner', 'Transfer to Owner'), ('transfer_admin', 'Transfer to Admin'), ('charge_deposit', 'Charge Deposit'), ('refund', 'Refund'), ('checkout', 'Check Out'), ('capture', 'Capture Payment')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paymenttask',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'type'), name='unique_task_type_per_reservation'),
        ),
    ]
