# Generated by Django 5.2 on 2025-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_paymenttask_unique_task_type_per_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttask',
            name='type',
            field=models.CharField(choices=[('transfer_owner', 'Transfer to Owner'), ('transfer_admin', 'Transfer to Admin'), ('charge_deposit', 'Charge Deposit'), ('refund', 'Refund'), ('checkout', 'Check Out'), ('capture', 'Capture Payment'), ('create_manual_payment_intent', 'Create Manual Payment Intent'), ('create_setup_intent', 'Create Setup Intent')], max_length=32),
        ),
    ]
