# Generated by Django 5.2 on 2025-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymenttask_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttask',
            name='type',
            field=models.CharField(choices=[('transfer_owner', 'Transfer to Owner'), ('transfer_admin', 'Transfer to Admin'), ('transfer_deposit_owner', 'Transfer Deposit to Owner'), ('charge_deposit', 'Charge Deposit'), ('refund', 'Refund'), ('checkout', 'Check Out'), ('capture', 'Capture Payment'), ('create_manual_payment_intent', 'Create Manual Payment Intent'), ('create_setup_intent', 'Create Setup Intent')], max_length=32),
        ),
    ]
