# Generated by Django 5.2 on 2025-06-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HueyFakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Huey (Tâches en file)',
                'verbose_name_plural': 'Huey (Tâches en file)',
                'managed': False,
            },
        ),
    ]
