# Generated by Django 5.2 on 2025-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_taskhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-started_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='args',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='kwargs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['task_id'], name='common_task_task_id_72fea1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['name'], name='common_task_name_e6fdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['status'], name='common_task_status_354343_idx'),
        ),
    ]
