# Generated by Django 5.2 on 2025-06-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_taskhistory_options_taskhistory_args_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HueyFakeModel',
        ),
    ]
