# Generated by Django 5.2 on 2025-06-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='category',
            field=models.CharField(choices=[('main', 'Résidence Principale'), ('secondary', 'Résidence Secondaire')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='logement',
            name='registered_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
