# Generated by Django 5.2 on 2025-06-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0002_logement_category_logement_registered_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='registration',
            field=models.BooleanField(default=False),
        ),
    ]
