# Generated by Django 5.2 on 2025-06-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0003_city_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='registered_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
