# Generated by Django 5.2 on 2025-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0004_alter_logement_registered_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
