# Generated by Django 5.2 on 2025-06-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0005_logement_latitude_logement_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='min_booking_days',
            field=models.IntegerField(default=1),
        ),
    ]
