# Generated by Django 5.2 on 2025-06-13 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0006_logement_min_booking_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='ville',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='city', to='logement.city'),
            preserve_default=False,
        ),
    ]
