# Generated by Django 5.2 on 2025-06-13 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0007_alter_logement_ville'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('logement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logement.logement')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
