# Generated by Django 5.2 on 2025-06-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0008_platformfeewaiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformfeewaiver',
            name='logement',
        ),
    ]
