# Generated by Django 5.2 on 2025-07-04 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0009_remove_platformfeewaiver_logement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogementRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.PositiveSmallIntegerField(default=0, help_text='Propreté (1-5)')),
                ('equipment', models.PositiveSmallIntegerField(default=0, help_text='Équipement (1-5)')),
                ('location', models.PositiveSmallIntegerField(default=0, help_text='Emplacement (1-5)')),
                ('welcome', models.PositiveSmallIntegerField(default=0, help_text='Accueil (1-5)')),
                ('value', models.PositiveSmallIntegerField(default=0, help_text='Rapport qualité/prix (1-5)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='logement.logement')),
            ],
        ),
    ]
