# Generated by Django 5.2 on 2025-07-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0010_logementranking'),
        ('reservation', '0009_alter_activityreservation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='logementranking',
            name='reservation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
            preserve_default=False,
        ),
    ]
