# Generated by Django 5.2 on 2025-07-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0011_logementranking_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logementranking',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='logement.logement'),
        ),
    ]
