# Generated by Django 5.2 on 2025-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0012_alter_logementranking_logement'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='self_check_in',
            field=models.BooleanField(default=False),
        ),
    ]
