# Generated by Django 5.2 on 2025-06-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Identifiant client Stripe associé pour paiements et impressions de carte.', max_length=255, null=True),
        ),
    ]
