# Generated by Django 5.2 on 2025-06-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default=1, help_text='Identifiant client Stripe associé pour paiements et impressions de carte.', max_length=255),
            preserve_default=False,
        ),
    ]
