# Generated by Django 5.2 on 2025-06-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
