# Generated by Django 5.2 on 2025-06-26 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_unique_admin_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Numéro au format international, ex: +33612345678', max_length=15, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone n'est pas valide. Veuillez entrer un numéro valide.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
