# Generated by Django 5.2 on 2025-06-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarded',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a terminé l'onboarding"),
        ),
    ]
