# Generated by Django 5.2 on 2025-06-03 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conciergerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la conciergerie')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='conciergeries/logos/')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('adresse', models.TextField(verbose_name='Adresse postale')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('forme_juridique', models.CharField(blank=True, max_length=100, verbose_name='Forme juridique')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='Numéro SIRET')),
                ('nom_representant', models.CharField(blank=True, max_length=255, verbose_name='Nom du représentant légal')),
                ('email_representant', models.EmailField(blank=True, max_length=254, verbose_name='Email du représentant')),
                ('telephone_representant', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du représentant')),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True)),
                ('validated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciergeries', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciergeries', to='logement.city')),
            ],
            options={
                'verbose_name': 'Conciergerie',
                'verbose_name_plural': 'Conciergeries',
                'ordering': ['name'],
            },
        ),
    ]
