# Generated by Django 5.2 on 2025-06-13 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0001_initial'),
        ('logement', '0007_alter_logement_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciergerie',
            name='ville',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='conciergeries', to='logement.city'),
            preserve_default=False,
        ),
    ]
