# Generated by Django 5.2 on 2025-06-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0002_alter_conciergerie_ville'),
        ('logement', '0008_platformfeewaiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergerieRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conciergerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='conciergerie.conciergerie')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciergerie_requests', to='logement.logement')),
            ],
        ),
    ]
