# Generated by Django 5.2 on 2025-06-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0003_conciergerierequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciergerie',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
