# Generated by Django 5.2 on 2025-06-15 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logement', '0008_platformfeewaiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Duration of the activity in minutes.')),
                ('start', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('cancelation_period', models.PositiveIntegerField(default=7, help_text='Number of days before the activity start when cancellation is allowed.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='logement.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_activities', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_activities', to='activity.category')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.PositiveIntegerField(default=1)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20)),
                ('start', models.DateTimeField()),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_fee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_saved_payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('refunded', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transferred', models.BooleanField(default=False)),
                ('transferred_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_checkin_email_sent', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='activity.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la conciergerie')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='conciergeries/logos/')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('adresse', models.TextField(verbose_name='Adresse postale')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('forme_juridique', models.CharField(blank=True, max_length=100, verbose_name='Forme juridique')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='Numéro SIRET')),
                ('nom_representant', models.CharField(blank=True, max_length=255, verbose_name='Nom du représentant légal')),
                ('email_representant', models.EmailField(blank=True, max_length=254, verbose_name='Email du représentant')),
                ('telephone_representant', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du représentant')),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True)),
                ('validated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_partners', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_partners', to='logement.city')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['name'],
            },
        ),
    ]
