# Generated by Django 5.2 on 2025-06-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='start',
        ),
    ]
