# Generated by Django 5.2 on 2025-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_activity_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='availablity_period',
            field=models.PositiveIntegerField(default=1, help_text='Number of days required to prepare the activity.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/logos/'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du partenaire'),
        ),
    ]
