# Generated by Django 5.2 on 2025-06-16 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_availablity_period_alter_activity_is_active_and_more'),
        ('logement', '0009_remove_platformfeewaiver_logement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='availablity_period',
        ),
        migrations.AddField(
            model_name='activity',
            name='availability_period',
            field=models.PositiveIntegerField(default=1, help_text="Nombre de jours nécessaires à la préparation de l'activité.", verbose_name='Préavis (jours)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cancelation_period',
            field=models.PositiveIntegerField(default=7, help_text="Nombre de jours avant le début de l'activité où l'annulation est possible.", verbose_name="Délai d'annulation (jours)"),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_activities', to='activity.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name="Description de l'activité"),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(help_text="Durée totale de l'activité en minutes.", verbose_name='Durée (minutes)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activité active ?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='logement.city', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(verbose_name='Nombre maximum de participants'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Nom de l'activité"),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix (€)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.CreateModel(
            name='CloseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_dates', to='activity.activity')),
            ],
        ),
    ]
