# Generated by Django 5.2 on 2025-06-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_activity_availablity_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fee_per_extra_guest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais supplémentaires pour chaque participant au-delà du nombre nominal.', max_digits=6, verbose_name='Frais par participant supplémentaire (€)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='nominal_guests',
            field=models.PositiveIntegerField(default=1, help_text="Nombre de participants par défaut pour l'activité.", verbose_name='Nombre de participants'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='activity.activity')),
            ],
        ),
    ]
