# Generated by Django 5.2 on 2025-06-16 15:13

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_activity_fee_per_extra_guest_activity_nominal_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], default=[], help_text="Jours de la semaine où l'activité est disponible.", max_length=56, verbose_name='Jours de la semaine'),
        ),
        migrations.AddField(
            model_name='activity',
            name='end',
            field=models.TimeField(default='18:00', help_text="Heure de fin de l'activité dans la journée.", verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='activity',
            name='ready_period',
            field=models.PositiveIntegerField(default=0, help_text='Temps minimum entre deux réservations de cette activité.', verbose_name='Délai entre deux activités (minutes)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start',
            field=models.TimeField(default='09:00', help_text="Heure de début de l'activité dans la journée.", verbose_name='Heure de début'),
        ),
    ]
