# Generated by Django 5.2 on 2025-06-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_days_of_week_activity_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fixed_slots',
            field=models.BooleanField(default=False, help_text='Activité à horaire fixe', verbose_name='Horaires Fixes'),
        ),
        migrations.AddField(
            model_name='activity',
            name='manual_time_slots',
            field=models.TextField(blank=True, help_text='Entrez chaque créneau horaire sur une ligne séparée, au format HH:MM (ex: 09:00).', verbose_name='Créneaux horaires personnalisés'),
        ),
    ]
