# Generated by Django 5.2 on 2025-06-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_activity_fixed_slots_activity_manual_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activité ouverte ?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='manual_time_slots',
            field=models.TextField(blank=True, help_text='Entrez chaque créneau horaire sur une ligne séparée, au format HH:MM (ex: 09:00).', null=True, verbose_name='Créneaux horaires personnalisés'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ready_period',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Temps minimum entre deux réservations de cette activité.', null=True, verbose_name='Délai entre deux activités (minutes)'),
        ),
    ]
