# Generated by Django 5.2 on 2025-06-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_activity_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreservation',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
