# Generated by Django 5.2 on 2025-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_activityreservation_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreservation',
            name='status',
        ),
        migrations.AddField(
            model_name='activityreservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='pending', max_length=20),
        ),
    ]
