# Generated by Django 5.2 on 2025-06-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_remove_activityreservation_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityreservation',
            old_name='reservation_date',
            new_name='date_reservation',
        ),
    ]
