# Generated by Django 5.2 on 2025-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_rename_reservation_date_activityreservation_date_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreservation',
            name='stripe_saved_payment_method_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
