# Generated by Django 5.2 on 2025-06-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_remove_activityreservation_stripe_saved_payment_method_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='detail',
            field=models.TextField(default=1, verbose_name="Détails de l'activité"),
            preserve_default=False,
        ),
    ]
