# Generated by Django 5.2 on 2025-06-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_activity_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreservation',
            name='stripe_saved_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
