# Generated by Django 5.2 on 2025-06-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_activityreservation_stripe_saved_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreservation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
