# Generated by Django 5.2 on 2025-06-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_activityreservation_accepted_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityReservation',
        ),
    ]
