# Generated by Django 5.2 on 2025-06-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_delete_activityreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
