from django.core.management.base import BaseCommand
from logement.models import Equipment

EQUIPMENT_DATA = [
    ("Accès mobilité réduite", "fa-wheelchair", "comfort"),
    ("Machine à laver", "fas fa-soap", "bed_bath"),
    ("Garage", "fas fa-car", "parking"),
    ("Étendoir à linge", "fas fa-tshirt", "bed_bath"),
    ("Équipements de cuisine de base", "fas fa-utensils", "kitchen"),
    ("Équipements de base", "fas fa-toilet-paper", "comfort"),
    ("Écran coupe-feu", "fas fa-shield-alt", "security"),
    ("Wifi", "fas fa-wifi", "connectivity"),
    ("Vélos pour enfants", "fas fa-bicycle", "children"),
    ("Vélos", "fas fa-bicycle", "outdoor"),
    ("Verres à vin", "fas fa-wine-glass", "kitchen"),
    ("Ventilateurs portables", "fas fa-fan", "climate"),
    ("Ventilateur de plafond", "fas fa-fan", "climate"),
    ("Vaisselle pour enfants", "fas fa-utensil-spoon", "children"),
    ("Vaisselle et couverts", "fas fa-utensils", "kitchen"),
    ("Ustensiles de barbecue", "fas fa-hotdog", "outdoor"),
    ("Télévision", "fas fa-tv", "entertainment"),
    ("Tourne disque", "fas fa-compact-disc", "entertainment"),
    ("Table à manger", "fas fa-utensils", "kitchen"),
    ("Table à langer", "fas fa-baby", "children"),
    ("Table de ping pong", "fas fa-table-tennis", "entertainment"),
    ("Séjours longue durée autorisés", "fas fa-calendar-alt", "other"),
    ("Sèche-linge", "fas fa-soap", "bed_bath"),
    ("Sèche-cheveux", "fas fa-wind", "bed_bath"),
    ("Système audio", "fas fa-volume-up", "entertainment"),
    ("Stores", "fas fa-blinds", "comfort"),
    ("Stationnement payant à l'extérieur de la propriété", "fas fa-parking", "parking"),
    (
        "Station de recharge pour véhicules électriques",
        "fas fa-charging-station",
        "parking",
    ),
    ("Shampooing", "fas fa-pump-soap", "bed_bath"),
    ("Savon pour le corps", "fas fa-pump-soap", "bed_bath"),
    ("Sauna", "fas fa-hot-tub", "wellness"),
    ("Salon privé", "fas fa-couch", "comfort"),
    ("Salle de sport", "fas fa-dumbbell", "wellness"),
    ("Salle de jeux pour enfants", "fas fa-child", "children"),
    ("Réfrigérateur", "fas fa-icicles", "kitchen"),
    ("Recommandations de baby-sitters", "fas fa-baby", "children"),
    ("Protections sur les fenêtres", "fas fa-window-maximize", "security"),
    ("Protections sur les coins de tables", "fas fa-ruler-combined", "security"),
    ("Produits indispensables pour la plage", "fas fa-umbrella-beach", "outdoor"),
    ("Produits de nettoyage", "fas fa-pump-soap", "cleaning"),
    ("Plaque de cuisson", "fas fa-fire", "kitchen"),
    ("Piste de bowling", "fas fa-bowling-ball", "entertainment"),
    ("Piscine", "fas fa-swimmer", "wellness"),
    ("Piano", "fas fa-music", "entertainment"),
    ("Petit déjeuner", "fas fa-egg", "kitchen"),
    ("Terasse ou balcon", "fas fa-chair", "outdoor"),
    ("Patinoire de hockey", "fas fa-hockey-puck", "entertainment"),
    ("Parking payant sur place", "fas fa-parking", "parking"),
    ("Parking gratuit sur place", "fas fa-parking", "parking"),
    ("Parking gratuit dans la rue", "fas fa-parking", "parking"),
    ("Oreillers et couvertures supplémentaires", "fas fa-blanket", "bed_bath"),
    ("Ménage disponible pendant le séjour", "fas fa-broom", "cleaning"),
    ("Moustiquaire", "fas fa-window-close", "comfort"),
    ("Mobilier d'extérieur", "fas fa-chair", "outdoor"),
    ("Mini réfrigérateur", "fas fa-icicles", "kitchen"),
    ("Machine à pain", "fas fa-bread-slice", "kitchen"),
    ("Logement de plain-pied", "fas fa-home", "comfort"),
    ("Livres et jouets pour enfants", "fas fa-puzzle-piece", "children"),
    ("Livres et de quoi lire", "fas fa-book", "entertainment"),
    ("Lit pour bébé", "fas fa-baby", "children"),
    ("Lit parapluie", "fas fa-bed", "children"),
    ("Laverie automatique à proximité", "fas fa-tshirt", "cleaning"),
    ("Lave-vaisselle", "fas fa-sink", "kitchen"),
    ("Lave-linge", "fas fa-soap", "bed_bath"),
    ("Laser game", "fas fa-bullseye", "entertainment"),
    ("Kitchenette", "fas fa-utensils", "kitchen"),
    ("Kit de premiers secours", "fas fa-briefcase-medical", "security"),
    ("Jeux géants", "fas fa-chess", "entertainment"),
    ("Jeux de société", "fas fa-puzzle-piece", "entertainment"),
    ("Jeux d'arcade", "fas fa-gamepad", "entertainment"),
    ("Jacuzzi", "fas fa-hot-tub", "wellness"),
    ("Hamac", "fas fa-water", "outdoor"),
    ("Grille-pain", "fas fa-bread-slice", "kitchen"),
    ("Gel douche", "fas fa-pump-soap", "bed_bath"),
    ("Front de mer", "fas fa-water", "outdoor"),
    ("Four à micro-ondes", "fas fa-burn", "kitchen"),
    ("Four", "fas fa-oven", "kitchen"),
    ("Fer à repasser", "fas fa-stream", "bed_bath"),
    ("Extincteur", "fas fa-fire-extinguisher", "security"),
    ("Espace repas en plein air", "fas fa-utensils", "outdoor"),
    ("Espace de travail dédié", "fas fa-laptop", "connectivity"),
    ("Espace de rangement pour les vêtements", "fas fa-box", "bed_bath"),
    ("Entrée privée", "fas fa-door-open", "comfort"),
    ("Eau chaude", "fas fa-tint", "comfort"),
    ("Détecteur de monoxyde de carbone", "fas fa-exclamation-triangle", "security"),
    ("Détecteur de fumée", "fas fa-bell", "security"),
    ("Dépôt de bagages autorisé", "fas fa-suitcase", "comfort"),
    ("Draps", "fas fa-bed", "bed_bath"),
    ("Servettes de bain", "fas fa-bed", "bed_bath"),
    ("Servettes de plage", "fas fa-bed", "outdoor"),
    ("Douche extérieure", "fas fa-shower", "bed_bath"),
    ("Cuisinière", "fas fa-fire", "kitchen"),
    ("Cuisine extérieure", "fas fa-hotdog", "kitchen"),
    ("Cuisine", "fas fa-utensils", "kitchen"),
    ("Cuiseur à riz", "fas fa-utensils", "kitchen"),
    ("Console de jeu", "fas fa-gamepad", "entertainment"),
    ("Connexion Ethernet", "fas fa-network-wired", "connectivity"),
    ("Congélateur", "fas fa-snowflake", "kitchen"),
    ("Compacteur de déchets", "fas fa-trash", "cleaning"),
    ("Coffre-fort", "fas fa-lock", "security"),
    ("Climatisation", "fas fa-snowflake", "climate"),
    ("Cinéma", "fas fa-film", "entertainment"),
    ("Cintres", "fas fa-tshirt", "bed_bath"),
    ("Cheminée", "fas fa-fireplace", "comfort"),
    ("Chauffage", "fas fa-fire", "climate"),
    ("Chaises longues", "fas fa-couch", "outdoor"),
    ("Chaise haute", "fas fa-chair", "children"),
    ("Matelas haut de gamme", "fas fa-bed", "bed_bath"),
    ("Café", "fas fa-mug-hot", "kitchen"),
    ("Cafetière", "fas fa-coffee", "kitchen"),
    ("Oreillers mémoire de forme", "fas fa-bed", "bed_bath"),
    ("Couette hypoallergénique", "fas fa-allergies", "bed_bath"),
    ("Caches-prises", "fas fa-plug", "security"),
    ("Brasero", "fas fa-fire-alt", "outdoor"),
    ("Bouilloire électrique", "fas fa-mug-hot", "kitchen"),
    ("Blender", "fas fa-blender", "kitchen"),
    ("Billard", "fas fa-bowling-ball", "entertainment"),
    ("Bidet", "fas fa-toilet", "bed_bath"),
    ("Barrières de sécurité pour bébé", "fas fa-shield-alt", "children"),
    ("Barbecue", "fas fa-fire", "outdoor"),
    ("Baignoire pour bébés", "fas fa-baby", "children"),
    ("Baignoire", "fas fa-bath", "bed_bath"),
    ("Babyphone", "fas fa-broadcast-tower", "children"),
    ("Ascenseur", "fas fa-elevator", "comfort"),
    ("Arrière-cour", "fas fa-tree", "outdoor"),
    ("Après-shampoing", "fas fa-pump-soap", "bed_bath"),
    ("Appareils de fitness", "fas fa-dumbbell", "wellness"),
    ("Aire de jeux extérieure", "fas fa-child", "children"),
    ("Accès à la plage", "fas fa-umbrella-beach", "outdoor"),
    ("Accès au lac", "fas fa-water", "outdoor"),
    ("Accessible à skis", "fas fa-skiing", "outdoor"),
]


class Command(BaseCommand):
    help = "Importe les équipements standards"

    def handle(self, *args, **kwargs):
        for name, icon, equip_type in EQUIPMENT_DATA:
            obj, created = Equipment.objects.get_or_create(name=name)
            obj.icon = icon
            obj.type = equip_type  # Requires you to have added a 'type' field to Equipment model
            obj.save()
        self.stdout.write(
            self.style.SUCCESS("✔️ Équipements importés avec succès avec type")
        )
