from django.core.management.base import BaseCommand
from logement.models import Equipment

EQUIPMENT_DATA = [
    ("Accessible à skis", "fas fa-skiing"),
    ("Accès au complexe hôtelier", "fas fa-hotel"),
    ("Accès au lac", "fas fa-water"),
    ("Accès à la plage", "fas fa-umbrella-beach"),
    ("Aire de jeux extérieure", "fas fa-child"),
    ("Appareils de fitness", "fas fa-dumbbell"),
    ("Après-shampoing", "fas fa-pump-soap"),
    ("Arrière-cour", "fas fa-tree"),
    ("Ascenseur", "fas fa-elevator"),
    ("Babyphone", "fas fa-broadcast-tower"),
    ("Baignoire", "fas fa-bath"),
    ("Baignoire pour bébés", "fas fa-baby"),
    ("Barbecue", "fas fa-fire"),
    ("Barrières de sécurité pour bébé", "fas fa-shield-alt"),
    ("Bidet", "fas fa-toilet"),
    ("Billard", "fas fa-bowling-ball"),
    ("Blender", "fas fa-blender"),
    ("Bouilloire électrique", "fas fa-mug-hot"),
    ("Brasero", "fas fa-fire-alt"),
    ("Caches-prises", "fas fa-plug"),
    ("Cafetière", "fas fa-coffee"),
    ("Café", "fas fa-mug-hot"),
    ("Cage d'entraînement de baseball", "fas fa-baseball-ball"),
    ("Cale de mise à l'eau pour bateaux", "fas fa-ship"),
    ("Chaise haute", "fas fa-chair"),
    ("Chaises longues", "fas fa-couch"),
    ("Chauffage", "fas fa-fire"),
    ("Cheminée", "fas fa-fireplace"),
    ("Cintres", "fas fa-tshirt"),
    ("Cinéma", "fas fa-film"),
    ("Climatisation", "fas fa-snowflake"),
    ("Coffre-fort", "fas fa-lock"),
    ("Compacteur de déchets", "fas fa-trash"),
    ("Congélateur", "fas fa-snowflake"),
    ("Connexion Ethernet", "fas fa-network-wired"),
    ("Console de jeu", "fas fa-gamepad"),
    ("Cuiseur à riz", "fas fa-utensils"),
    ("Cuisine", "fas fa-utensils"),
    ("Cuisine extérieure", "fas fa-hotdog"),
    ("Cuisinière", "fas fa-fire"),
    ("Douche extérieure", "fas fa-shower"),
    ("Draps", "fas fa-bed"),
    ("Dépôt de bagages autorisé", "fas fa-suitcase"),
    ("Détecteur de fumée", "fas fa-bell"),
    ("Détecteur de monoxyde de carbone", "fas fa-exclamation-triangle"),
    ("Eau chaude", "fas fa-tint"),
    ("Entrée privée", "fas fa-door-open"),
    ("Espace de rangement pour les vêtements", "fas fa-box"),
    ("Espace de travail dédié", "fas fa-laptop"),
    ("Espace repas en plein air", "fas fa-utensils"),
    ("Extincteur", "fas fa-fire-extinguisher"),
    ("Fer à repasser", "fas fa-stream"),
    ("Four", "fas fa-oven"),
    ("Four à micro-ondes", "fas fa-burn"),
    ("Front de mer", "fas fa-water"),
    ("Gel douche", "fas fa-pump-soap"),
    ("Grille-pain", "fas fa-bread-slice"),
    ("Hamac", "fas fa-water"),
    ("Jacuzzi", "fas fa-hot-tub"),
    ("Jeux d'arcade", "fas fa-gamepad"),
    ("Jeux de société", "fas fa-puzzle-piece"),
    ("Jeux géants", "fas fa-chess"),
    ("Kayak", "fas fa-water"),
    ("Kit de premiers secours", "fas fa-briefcase-medical"),
    ("Kitchenette", "fas fa-utensils"),
    ("Laser game", "fas fa-bullseye"),
    ("Lave-linge", "fas fa-soap"),
    ("Lave-vaisselle", "fas fa-sink"),
    ("Laverie automatique à proximité", "fas fa-tshirt"),
    ("Lit parapluie", "fas fa-bed"),
    ("Lit pour bébé", "fas fa-baby"),
    ("Livres et de quoi lire", "fas fa-book"),
    ("Livres et jouets pour enfants", "fas fa-puzzle-piece"),
    ("Logement de plain-pied", "fas fa-home"),
    ("Machine à pain", "fas fa-bread-slice"),
    ("Mini réfrigérateur", "fas fa-icicles"),
    ("Minigolf", "fas fa-golf-ball"),
    ("Mobilier d'extérieur", "fas fa-chair"),
    ("Moustiquaire", "fas fa-window-close"),
    ("Mur d'escalade", "fas fa-mountain"),
    ("Ménage disponible pendant le séjour", "fas fa-broom"),
    ("Oreillers et couvertures supplémentaires", "fas fa-blanket"),
    ("Parking gratuit dans la rue", "fas fa-parking"),
    ("Parking gratuit sur place", "fas fa-parking"),
    ("Parking payant sur place", "fas fa-parking"),
    ("Patinoire de hockey", "fas fa-hockey-puck"),
    ("Patio ou balcon", "fas fa-chair"),
    ("Petit déjeuner", "fas fa-egg"),
    ("Piano", "fas fa-music"),
    ("Piscine", "fas fa-swimmer"),
    ("Piste de bowling", "fas fa-bowling-ball"),
    ("Pièce à thème", "fas fa-theater-masks"),
    ("Plaque de cuisson", "fas fa-fire"),
    ("Produits de nettoyage", "fas fa-pump-soap"),
    ("Produits indispensables pour la plage", "fas fa-umbrella-beach"),
    ("Protections sur les coins de tables", "fas fa-ruler-combined"),
    ("Protections sur les fenêtres", "fas fa-window-maximize"),
    ("Rampe de skateboard", "fas fa-skating"),
    ("Recommandations de baby-sitters", "fas fa-baby"),
    ("Réfrigérateur", "fas fa-icicles"),
    ("Salle de jeux pour enfants", "fas fa-child"),
    ("Salle de sport", "fas fa-dumbbell"),
    ("Salon privé", "fas fa-couch"),
    ("Sauna", "fas fa-hot-tub"),
    ("Savon pour le corps", "fas fa-pump-soap"),
    ("Shampooing", "fas fa-pump-soap"),
    ("Station de recharge pour véhicules électriques", "fas fa-charging-station"),
    ("Stationnement payant à l'extérieur de la propriété", "fas fa-parking"),
    ("Stores", "fas fa-blinds"),
    ("Système audio", "fas fa-volume-up"),
    ("Sèche-cheveux", "fas fa-wind"),
    ("Sèche-linge", "fas fa-soap"),
    ("Séjours longue durée autorisés", "fas fa-calendar-alt"),
    ("Table de ping pong", "fas fa-table-tennis"),
    ("Table à langer", "fas fa-baby"),
    ("Table à manger", "fas fa-utensils"),
    ("Tourne disque", "fas fa-compact-disc"),
    ("Télévision", "fas fa-tv"),
    ("Ustensiles de barbecue", "fas fa-hotdog"),
    ("Vaisselle et couverts", "fas fa-utensils"),
    ("Vaisselle pour enfants", "fas fa-utensil-spoon"),
    ("Ventilateur de plafond", "fas fa-fan"),
    ("Ventilateurs portables", "fas fa-fan"),
    ("Verres à vin", "fas fa-wine-glass"),
    ("Vélos", "fas fa-bicycle"),
    ("Vélos pour enfants", "fas fa-bicycle"),
    ("Wi-Fi portable", "fas fa-wifi"),
    ("Wifi", "fas fa-wifi"),
    ("Écran coupe-feu", "fas fa-shield-alt"),
    ("Équipements de base", "fas fa-toilet-paper"),
    ("Équipements de cuisine de base", "fas fa-utensils"),
    ("Étendoir à linge", "fas fa-tshirt"),
]


class Command(BaseCommand):
    help = "Importe les équipements standards"

    def handle(self, *args, **kwargs):
        for equip in EQUIPMENT_DATA:
            obj, created = Equipment.objects.get_or_create(name=equip[0])
            obj.icon = equip[1]
            obj.save()
        self.stdout.write(self.style.SUCCESS("✔️ Équipements importés avec succès"))
