# Generated by Django 5.2 on 2025-06-03 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='airbnb_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logement.logement')),
            ],
        ),
        migrations.CreateModel(
            name='booking_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logement.logement')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée'), ('echec_paiement', 'Echec du paiement')], default='en_attente', max_length=20)),
                ('guest', models.IntegerField()),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_fee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('admin_fee_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_saved_payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('caution_charged', models.BooleanField(default=False)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('stripe_deposit_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transferred', models.BooleanField(default=False)),
                ('transferred_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('admin_stripe_transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_transferred', models.BooleanField(default=False)),
                ('admin_transferred_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('logement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logement.logement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
