# Generated by Django 5.2 on 2025-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pre_checkin_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
