# Generated by Django 5.2 on 2025-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_pre_checkin_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest',
            new_name='guest_adult',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_minor',
            field=models.IntegerField(default=0),
        ),
    ]
