# Generated by Django 5.2 on 2025-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_guest_reservation_guest_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
