# Generated by Django 5.2 on 2025-06-22 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_delete_activityreservation'),
        ('reservation', '0006_reservation_accepted_at_reservation_cgu_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.PositiveIntegerField(default=1)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='pending', max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_fee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_saved_payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('refunded', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transferred', models.BooleanField(default=False)),
                ('transferred_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_checkin_email_sent', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cgu_version', models.CharField(blank=True, max_length=20, null=True)),
                ('cgv_version', models.CharField(blank=True, max_length=20, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='activity.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
