# Generated by Django 5.2 on 2025-06-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_activityreservationhistory_reservationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée'), ('echec_paiement', 'Échec du paiement')], default='pending', max_length=20),
        ),
    ]
