# Generated by Django 5.2 on 2025-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_activityreservation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='caution_transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_transferred_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='reservation',
            name='stripe_deposit_transfer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
