# Generated by Django 5.2 on 2025-06-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
